services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: traveloop_dev
      POSTGRES_USER: traveloop
      POSTGRES_PASSWORD: traveloop
    ports:
      - "5432:5432"
    volumes:
      - traveloop_pg_data:/var/lib/postgresql/data

volumes:
  traveloop_pg_data:
